# Generated by Django 4.1.5 on 2023-01-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categories',
            new_name='category',
        ),
    ]
