# Generated by Django 4.1.5 on 2023-02-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_categories_expense_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['-created_at']},
        ),
    ]
